### ISSUE TITLE
Is it possible to access Windows DLLs straight from Lily?

### ISSUE THREAD

**Issue by akavel** [FascinatedBox/lily#194]
I thought of trying to experiment with some WinAPI calls, but couldn't find info if it's possible. From that I assume it's not, but thought I might as well ask. Ideally, I'd be interested in accessing them without having to write a wrapper package in C, with each WinAPI function needing a manually crafted wrapper. Would also necessitate various FFI-related low-level mechanisms, such as: creating byte-by-byte controlled structures in memory; passing pinned pointers to memory locations to WinAPI & into the structs; ideally emitting C-protocol (stdcall/cdecl, I don't remember) functions/wrappers for Lily functions, to be passed to WinAPI. So, probably lots of work :)

Also, I've seen mention that one can somehow create packages for Lily in C, but haven't seen any docs on how to do that (tried browsing the Lily homepage, as well as the sources on github). Is there any guide for that?

**Comment by jesserayadkins** [comment]
At the moment, no. Everything is currently done by creating a wrapper package, and having that wrapper package provide a dynaload table for Lily to read in. I'm not familiar with the Windows API, but I'm reluctant to add something like this since I'd rather go the route of making it easier to add dynaload tables to bridge the gap. So I won't say a hard no, but only that I'd have to investigate and after a while.

Creating packages means, at the moment, creating dynaload tables by hand. It's messy, and it's not well documented anywhere. My plan was to wait until finishing up the api, and then to go back and document dynaload tables, how to create functions to interface with Lily, etc.

**Comment by akavel** [comment]
Thanks for the response!

**Comment by FascinatedBox** [comment]
I left this open in case I changed my mind and no, I don't think this is likely to happen. I'd much rather people creating a binding library that uses dynaload.
