### ISSUE TITLE
Syntax for matching in methods in dotted enums isn't obvious

### ISSUE THREAD

**Issue by radiofreejohn** [FascinatedBox/lily#211]
In "normal" enums, the matching is pretty straight forward, but dotted enums seem to have an inconsistency with how the variants are referred to in case statements.

For example, this is straight forward:

```
enum Speed {
    Fast
    Medium
    Slow

    define slow_down: Speed
    {
        match self: {
            case Fast: return Medium
            case Medium: return Slow
            case Slow: return Slow
        }
    }  
}

print(Fast.slow_down()) # Medium
```

This is less clear to me since the variant is used without the dotted notation in the case match, but cannot be used the same way in the return:

```
enum Speed {
    .Fast
    .Medium
    .Slow

    define slow_down: Speed
    {
        match self: {
            case Fast: return Speed.Medium
            case Medium: return Speed.Slow
            case Slow: return Speed.Slow
        }
    }  
}

print(Speed.Fast.slow_down())
```

I don't know if this is "wrong" or if there is a right thing to do, but I would have expected to use the dotted notation within the method like so:

```
        match self: {
            case .Fast: return .Medium
            case .Medium: return .Slow
            case .Slow: return .Slow
        }
```

Or none at all, and keep it similar to the non dotted syntax.

As a complete aside, I would have also expected the output of this to be the full enum:

```
# actual
print(Speed.Fast) # Fast
# expected
print(Speed.Fast) # Speed.Fast
```

**Comment by jesserayadkins** [comment]
To your first point, I'm not so sure about it. Requiring the dot during declaration is about making it abundantly clear that you intend for the enums members to be scoped.

During match, now you're requiring the dots, but...is it necessary? Could it be seen as a convenience that the interpreter doesn't require you to scope the variants because it knows what it's matching against?

The last one, I agree. I'm wanting to alter enums and variants internally a little bit, and I can fix that along the way.

**Comment by radiofreejohn** [comment]
During match I'm not too worried if dots should be required only that it's consistent. Right now the case needs no dots but he return needs dots. I'd prefer either always using dots or never.

**Comment by jesserayadkins** [comment]
Being able to refer to variants like that is something that Swift can do, and I'd like to see Lily eventually do it. Going to make an issue now.

**Comment by jesserayadkins** [comment]
Since this is a little broad (and it's now answered by a couple of smaller issues), I'll close this and get to those two issues as time permits.

**Comment by FascinatedBox** [comment]
Since 1.0 is coming out recently, I've been thinking more about enums and scoping. You make a good point about consistency. A little while I also thought of this case:

```
class Test {}

scoped enum Example { Test, Whatever }
```

It's contrived, but I think serves as a case to bolster the point: It should be `Example.Test` in all cases, to avoid a potential conflict with a `Test` class.

It's also consistent, and I like consistency.
