### ISSUE TITLE
Better String handling through utf8proc

### ISSUE THREAD

**Issue by FascinatedBox** [FascinatedBox/lily#213]
Lily's handling of Strings is pretty awful right now. I've taken a look around, and I'd like to use utf8proc be used to make Lily's Strings better.

I don't have a complete idea of what I want, but for the basics, I'd like to be able to each over bytes (so, Bytes need to come in first), over code points (maybe pushing back Integer?), and definitely to each over graphemes.

This might include support for a new Grapheme type, the same way that Swift has that.

**Comment by stevedonovan** [comment]
You've chosen the hard route to follow - proper UTF-8 out of the box, which is good. Golang defines 'rune' as its extended character type.  But I do know that _full_ UTF-8 support for _particular_ scripts is seriously complicated and a job for an iconv binding, etc. (E.g. what upper case means, etc. Wise to lean on the OS as much as possible).  Another wise decision is having a separate String (human text) and ByteString (anything else - bag of bytes).

While we're talking about strings, I'm missing a slice method. And I looked, but could not find a size method (which would be consistent with the lists and hashes). (Ditto for ByteString)

AFAIK, string concatenation is via string interpolation `$"^(a)^(b)" ?  Which also effectively defines the generic `tostring` operation as well?

**Comment by jesserayadkins** [comment]
I agree: Lily shouldn't be trying to do utf-8 itself, because utf-8 is very hard. But it needs to be done right from the get-go while there still aren't many people and there's no band-aid that needs to be ripped off.

For your second part, I haven't done much work with either String or ByteString. So there's a lot missing. It's not even possible to query the length of a String!

For slice, there's a question of what you're starting from. A byte boundary? Code point offset? Grapheme offset? For ByteStrings, it seems natural for operations to be based on byte boundaries.

I think I'll add concatenation through interpolation somewhere in the documentation, unless you're interested in doing so. I've noticed it's a semi-frequent question, which I see as a hole in the documentation.

Interpolation uses built-in magic for getting the string representation of a value, and isn't reliant on and to_s/toString nethod being present.

**Comment by stevedonovan** [comment]
Yes, ByteStrings are easy.  With a String I'd expect 'character' offsets in a slice, size of String ought to be in 'characters' as well.  Then `find` ought to return char offset.  It seems important to be consistent. Have a look at the Go strings package: https://golang.org/pkg/strings/ - Go string handling was fun to use, and these are the guys that invented UTF-8 back in Bell Labs.

'single quote strings' aren't supported, which is a pity. They can be convenient when quoting things. Talking of interpolation, the Boo language (second-greatest programming language from Brazil, pity about name) used double-quotes for strings that interpolated, single-quotes for strings that did not - consistent with the Unix shell. But that might be a bit too disruptive.

**Comment by FascinatedBox** [comment]
It's been quite some time since I opened this. Since then, I've done a number of improvements to String. One complaint I have of this issue is that it's overly broad, and thus hard to define when it's been done good enough. I've added a couple of issues for what I see as the two biggest problems right now. In the meantime, I'm closing this.
