### ISSUE TITLE
Add unsigned integer types

### ISSUE THREAD

**Issue by archshift** [FascinatedBox/lily#222]
Unsigned integers are essential when working with any sort of binary formats, and for proper interop with C.

**Comment by jesserayadkins** [comment]
Having an unsigned type would be useful for crypto at least, and probably some hashing calculations. But I'd rather have a single unsigned type that's 64 bits or whatever bit size that Integer is (Someone embedding Lily might want 32 bit ints). Unsignedness would then be something you use only if you really need it.

Integer would need a conversion method: `Integer.to_u`, in the spirit of `to_s` and `to_d` since unsigned would be the only builtin type starting with U.

**Comment by FascinatedBox** [comment]
I've done more thinking about this, since the recent addition of `Byte`. I'm closing this because, for the moment, I don't see a use for an unsigned value within Lily. I'm worried about 1.0 including a type that doesn't have as much use as some of the other builtin types. About having to pull it later for not being as useful as expected. Perhaps another time, but not now.
