### ISSUE TITLE
Slight change to syntax error line reporting

### ISSUE THREAD

**Issue by stevedonovan** [FascinatedBox/lily#243]
```
SyntaxError: frodo has not been declared.
    from test-mod.lly:3
```

It would be most convenient for SciTE users if that line reference was 'test-mod.lly:3:', which is consistent with runtime errors. I know this is a very particular case, but SciTE is a popular editor and very easy to make Lily-friendly.

**Comment by jesserayadkins** [comment]
I left off the trailing colon (that's what you're asking for, right?) because there's nothing to put on the right side of it. I didn't want to put a function there because it would be __import__ or __main__ 99% of the time, and that's noise.

How does SciTE benefit from this, out of curiosity? The consistency is nice, but I'm wondering what the gain is.

**Comment by stevedonovan** [comment]
SciTE is a little unique because it has a set of predefined error-parsing rules in the output pane, unlike a more sane design where one provides a regular expression for each language's expected output. It's a minor niggle, really. '  from <file>:<n>' is just not one of the rules.

**Comment by jesserayadkins** [comment]
Seems like that would make it difficult to extend. But for this particular change, I don't have a real "no" in my mind. More of a shrug at best. The consistency argument helps a lot. So if you want to send a PR for this, I'll take it. Otherwise, I'll leave it until later (api is almost there).

**Comment by stevedonovan** [comment]
Yeah it's really pretty trivial in the larger scheme of things - the API is the important thing now.
