### ISSUE TITLE
A plan for coroutines (formerly: How about adding coroutines?)

### ISSUE THREAD

**Issue by DavidFeng** [FascinatedBox/lily#273]
like coroutine in Lua.

Lily is a language with very good design, thanks for your great work!

**Comment by FascinatedBox** [comment]
Thanks! For the moment, however, I don't have explicit plans for or against coroutines. I have ideas for interpreters being run from other interpreters. However, much of that will be some time away (when I've got time and energy for this once more). It's not something I'll do soon...I'd rather take some time and do a lot of research on what I want first.

**Comment by DavidFeng** [comment]
I will start reading this project as soon as I can, and I wish I could add feature I want for Lily

**Comment by FascinatedBox** [comment]
I've left this open for quite some time because I wasn't sure about it. Lily's internals were also moving often, so I was worried that coroutines would be caught up in the frequent churn. 1.2 solves the latter, but only has a month left before it's to be released, so it won't make the cut there.

**Comment by FascinatedBox** [comment]
I'm planning to get to this in the near future. Keyword arguments took some of the steam out of me so I'm going to pick on some of the easier features first.

I originally wanted to have them as a builtin library, but I think it's easier to have them be part of the builtin core.

Coroutines should look different from normal functions, so they'll use a different word than `define`. Right now I like how `codefine` sounds, even if it's close to `define`. Essentially, a coroutine is a function, able to have all of the nice function features, but with a different system under the hood.

Lua has an easier time of doing coroutines because it has multiple return types and, more importantly, it's dynamically-typed. Lily's more strict. A coroutine may only yield the same time it can return. In doing so, the caller can know what to expect.

A coroutine, like in Lua, can have one of three statuses: It's waiting (just started, or hasn't returned), it's done (it's returned), or it has an error. Since coroutines have their own stack (and their own state!) they can have their own errors. Errors generated in a coroutine shouldn't populate up to the caller.

However, if a caller tries to activate a coroutine that is in error or that is finished, then (and only then), should they receive an error (`RuntimeError`?).

A coroutine that yield some value must find a way to return a value. Even for infinite number generators, a value must always be returned. This is so that the interpreter has a way of deducing that the coroutine is indeed done.

Calling a coroutine that's been initialized will be done through a `call` method that takes as many arguments as the coroutine takes. In the above case, a basic `call` would produce a `Result` that has the coroutine's value on success, or an `Exception` on error. A usable coroutine would also provide `is_x` style functions to determine what the coroutine's status is.

Some caveats come to mind:

Coroutine states need to be linked together internally if they end up having their own function/class tables. Every coroutine needs to be updated when new code is evaluated to prevent one coroutine or another from having outdated info/using an array that's moved because it was realloc'd.

Coroutines and closures present a scary scenario, since I've had bad luck with closures in the past. I'm concerned about a coroutine sharing closure data with another, and that leading to a crash. Perhaps that can be alleviated by not allowing a coroutine inside of a coroutine (so that backing closure information is anchored in the 'main' area that will outlive coroutines).

Coroutines will need a different init than the current vm init which assumes there's a parser.

Coroutines that need to dynaload an exception would be an interesting interaction.

**Comment by FascinatedBox** [comment]
I'd like to apologize to anyone who's been waiting for this feature. I've dragged my feet on this to the point that the window for this release is almost up. Some of the reason has been a number of questions that coroutines have raised (in particular, what the api will look like). At this point, I think it's best to bump them to early next release so that there's time to work out whatever bugs may be present before the next release (another 3 months) is done.

I've done a lot of thinking of how coroutines will work, not just in the vm, but also in the type system. Consequently, I've come up with a number of changes to the last proposal. This, I'm quite confident, will be quite close to how coroutines will actually work.

To begin with, there will be no new keywords. No `yield` keyword, no `codefine` keyword, nada. Instead, most of the functionality will be in the `Coroutine` class described below.

Instead, a Function that wants to be a `Coroutine` will be written to take a `Coroutine` as a first argument. Here's an example of what this might look like:

```
define counter(co: Coroutine[Integer], start: Integer, stop: Integer): Integer {
    for i in start...stop - 1: {
        co.yield(i)
    }

    return stop
}

var counter_co = Coroutine.create(counter)(1, 10)

while counter_co.is_ready(): {
    match counter_co.resume(): {
        case Success(s):
            print("Counter yielded " ++ i ++ ".")
        case Failure(f):
            print("Counter failed?")
    }
}
```

This design is, I think, much more palatable than the previous iteration. I have a small amount of work done toward coroutines already, enough to prove that the above design is workable.

Dissecting the above example:

Functions that intend to be coroutines will have `Coroutine[(yield type)]` as their first argument.

A Function that acts as a coroutine will receive arguments only once (the call against the result of `Coroutine.create`).

`Coroutine.create` takes a Function that has a `Coroutine[x]` as a first argument and returns that same `x`. A coroutine is in one of a few states (ready, running, failed) and can be queried through is_* functions. I may also add a 'status' method if people have a use case for it, that would return the status as a simple `String`. I explicitly don't want the status to be an enum, because enums and variants are classes, and Lily already has a LOT of predefined classes.

I might also add a method to early-terminate a coroutine in a way that's more explicit to the caller (ex: `Coroutine.stop` raising a `StopCoroutine` exception), again if people want that.

`Coroutine.create`'s result is an intermediate builder function. The result of calling the builder with arguments is a new vm(!) with those arguments copied in. The builder can be called multiple times, each time yielding a new vm with whatever arguments are sent to it.

Why an intermediate builder and not have `Coroutine.create` do all the work? Simply put, the type system gets in the way. Lily currently understands `$1` as a magical type that accepts any types but also keeps track of what it accepts. So if a `Function` takes `$1` somewhere and later claims to return `$1`, the typing is preserved in the return. This was used, at one point, to have methods on `Tuple`.

The signature is something like this:

`static define Coroutine.create(fn: Function(Coroutine[A], $1 => A)): Function($1 => Coroutine[A])`

Lily knows how to solve `$1` when it's done processing a `Function`'s arguments. What it doesn't know how to do is to solve it AS it's processing arguments (telling it "the first argument is a `Function`, and based on that, take the arguments necessary to satisfy that function). Not only is that quite difficult, but I'm extremely wary of putting that kind of feature into the type system for such a narrow case. What if it has some bad interactions with other parts of the type system?


Given the uncertainties around coroutines and the testing that needs to be done around them, I think the responsible decision is to push them off until the next release. I'm hoping to finish them off early in the next release so any oversights can be addressed before the final version is done. Sorry.

**Comment by FascinatedBox** [comment]
Should be done with Coroutines by the end of next week. Some preliminary testing last night showed no surprises. I'll write up a blog post along with documentation about the feature once it's done.
