### ISSUE TITLE
mod_lily.so: White/blank page for example Lily template code

### ISSUE THREAD

**Issue by jonathonf** [FascinatedBox/lily#276]
mod_lily.so is installed and loaded in Apache 2.4.

```
# /usr/sbin/httpd -M
Loaded Modules:
 core_module (static)
 so_module (static)
 http_module (static)
 authn_file_module (shared)
...
 lily_module (shared)
```

Using the example template code,

``` html
<?lily
use server
?>
<html>
<body>
<?lily
server.write("Hello from mod_lily!")
?>
</body>
</html>
```

an entirely blank page is returned (no HTML, no errors). Apache's logs report a 200 which doesn't indicate any obvious permissions errors etc. Apache access log:

```
172.17.0.1 - - [12/Oct/2016:20:11:37 +0000] "GET /index.lly HTTP/1.1" 200 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
172.17.0.1 - - [12/Oct/2016:20:11:43 +0000] "GET /index.lly HTTP/1.1" 200 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
```

and response headers:

``` http
HTTP/1.1 200 OK
Date: Wed, 12 Oct 2016 20:08:44 GMT
Server: Apache/2.4.23 (Unix)
Content-Length: 0
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html
```

Running the file directly with `lily -t` gives:

``` bash
$ lily -t index.lly
SyntaxError: use has not been declared.
    from index.lly:2
```

Dockerfile for replicating (11MB image - Alpine is awesome): [Dockerfile.txt](https://github.com/FascinatedBox/lily/files/525533/Dockerfile.txt), then e.g.

``` bash
docker build -t alpine-lily .
docker run -dit -v ${HOME}/www:/www:ro -p 8000:80 alpine-lily
```

The module settings are essentially the same as those for the Alpine PHP5 and PHP7 modules (which both work fine), so they _should_ be correct.

I'm still open to this being user error but I can't see anything wrong with my setup...

**Comment by FascinatedBox** [comment]
This is a couple of problems.

The first, the actual fix, is that `use` should be replaced by `import`. I thought I had changed all `use`s to `import`s, but it seems I slipped. I'll push a fix for that later.

The other is that there ought to be a way to configure Lily to dump the error traceback, so that problems are easier to diagnose. I've been wary about enabling it as a default, for fear that someone might use runtime traceback to prod the website to reveal vulnerabilities. I'm interested as to any thoughts on that matter. Once this is closed (I'll leave it open as a reminder to fix the docs, as I'm going to be occupied for a few hours), I'll open up another issue to discuss traceback on Apache.

Supposing that replacing `use` with `import` doesn't work, then there's a deeper problem that I'll take a look at.

**Comment by stevedonovan** [comment]
One option is to make that error traceback conditional on some environment variable. 

I agree that seeing somebody else's stack trace in their web app seems ... tacky ;)

**Comment by jonathonf** [comment]
Ah, `import` works to an extent:

```html
1. 
2. <html>
3. <body>
4. Hello from mod_lily!
```

I can live with the extra whitespace but it does seem to be exiting after the final ?> closing tag... If I do

```html
<?lily
import server
?>
<html>
<body>
<?lily
server.write("Hello from mod_lily!")
?>
</body>
</html>
<?lily
?>
```
then I get the (more-or-less) expected output of

```html
1. 
2. <html>
3. <body>
4. Hello from mod_lily!
5. </body>
6. </html>
7. 
```
---
WRT errors, PHP's approach is to have an option or directive to say how much logging to do and where. While PHP's options can be set in a number of places (e.g. in a php.ini, an .htaccess file, or in the PHP page itself) I don't think that's necessary - just something like log_level({NONE, ERR, WARN, ALL}), whether in a page or server directive, would probably do.

Displaying errors is useful in a development environment, but something like configurable verbosity levels for stderr should do - I _think_ Apache will pick that up and include it in its default error_log.

**Comment by FascinatedBox** [comment]
It looks like, to begin with, you'd like to have the newline after `?>` not rendered in the final output, so that the output is more condensed. Supposing that's the case, I'm alright with that.

You mention exiting after the last closing tag, and I'm not quite sure what you mean. Do you mean that there's a different exit code from when the page ends up from `?>` instead of ending in html? It should be consistent there.

Now, there's the matter of error options. For that, I'd prefer to see Apache's configuration be used. Perhaps a 'show_traceback' option that's in mod_lily space, and used by mod_lily to determine if the trace is to be shown.

With regard to errors, how about adding `server.log` and `server.log_level` to the `server` api?

**Comment by FascinatedBox** [comment]
Closing this, since at the very least the original problem (use instead of import in the site docs) has been fixed.
