### ISSUE TITLE
BIGNUM support

### ISSUE THREAD

**Issue by jonathonf** [FascinatedBox/lily#287]
As at 0.18, `Integer` is a "wrapper over a C int64_t" [1]. There is no documented approach for use of larger numbers, and the current implementation will overflow (which isn't compatible with the goal of safety).

For example, Ruby's approach is to automatically promote overflowing `int`s within an Integer class that safely handles large numbers [2][3].

Lily needs either native support for large numbers, or a documented approach on how to use an alternative approach (e.g. libgmp via FFI).

[1] https://fascinatedbox.github.io/lily/reference.html
[2] https://bugs.ruby-lang.org/issues/12005
[3] https://ruby-doc.org/core-2.2.0/Bignum.html

**Comment by FascinatedBox** [comment]
I've never used a large number library, but my understanding is that usually it involves bringing GMP in, and that it's out of the range of what I can do. I'd prefer it if Lily's core stayed at zero dependencies, as it's then easier to port to different systems without having to be concerned over a package that you may not need, or fragmenting the language. There's also licensing.

I think it's best left as a library. Right now, I don't think Lily is prepared for it, because there's a lack of operator overloading that would make BigNum more palatable to look at. I'm still not sure if I want to even add that in.

Going back to overflow, I'd like to keep the current semantics of default operations keeping their unsafe behavior. One of Lily's focuses is safety, but I think there's a lot of code that doesn't need to check for overflow. Perhaps, in the future, a library or opt-in overflow-safe operators can be added.

**Comment by FascinatedBox** [comment]
I've added to the new site, in the tutorial, a mention of the lack of big number support: https://fascinatedbox.github.io/lily-site/tutorial.html#Literals

I don't see the language getting bignum support in core though.
