### ISSUE TITLE
Website link on repo is a 404

### ISSUE THREAD

**Issue by kirbyfan64** [FascinatedBox/lily#348]
https://fascinatedbox.github.io/lily-site/

**Comment by FascinatedBox** [comment]
Whoops, sorry about that. I took down the site some time ago because the data had a habit of getting stable since it wasn't linked to the core. Now the tutorial and most of the important bits are in the docs/ folder. The reference is on the gh-pages of this repo, and the sandbox is all that's left on the site.

Saying it all at once makes me think I should bring the site back at some point to unify all of it in one place. Maybe a script that decorates the markdown/html with a navbar. Hmm.

For the time being though, this is fixed. There are a few syntax-changing issues coming up, and I at least want to solve those before mucking about with the site again.

Thanks for noticing this. Also, nice avatar.
