### ISSUE TITLE
Various questions/suggestions for documentation

### ISSUE THREAD

**Issue by ghost** [FascinatedBox/lily#363]
I hope you don't mind this mixed bag of questions...

* What happens if the code is really deeply recursively nested? The online interpreter showed "unhandled exception: longjmp" in the console.
* Is it possible to expose foreign functions/data types manually to the interpreter without the bindgen tool? In cases one doesn't want to create a whole module but only register a few functions that are also used in a main program.
* Foreign pointers: How are they handled? Are they type checked as well, rendering it impossible to pass the wrong void* pointer to a foreign function?
* Can the interpreter be stopped by the host program? Without loss of data?
* (Theoretically speaking of course, given there was some kind of audit) how feasible do you think is it to point untrusted code sources like the internet towards a running interpreter? Easy? Hard? Architecturally impossible?

Thanks in advance!

**Comment by FascinatedBox** [comment]
Nothing wrong with that. Let's see:

> What happens if the code is really deeply nested? The online interpreter showed "unhandled exception: longjmp" in the console.

Deeply nested code should be throwing RuntimeError, not doing that.

> Is it possible to expose foreign functions/data types manually to the interpreter without the bindgen tool? In cases one doesn't want to create a whole module but only register a few functions that are also used in a main program.

No. Can't say I'm interested in doing so either. A small question would be how to register them, since the internals of the interpreter are based on modules each having a single registration table. A much bigger problem that this would pose, is that it would be harder to do swap-outs of different modules. One example: I've a small engine that can work in a browser (through emscriptenizing the interpreter and feeding it), or from the console. The engine works anywhere, however you want it to. The embedder only needs to supply a single ui package, and the engine provides some hooks in return for the embedder to call. I also like to know where symbols are coming from. When I import a package, I can control what symbols I take from it. If a package can add arbitrary symbols to some existing space (even if it's the main one), that's lost.

> Foreign pointers: How are they handled? Are they type checked as well, rendering it impossible to pass the wrong void* pointer to a foreign function?

If you're wanting to introduce foreign data to the interpreter, the best way is to wrap whatever you have into a struct with LILY_FOREIGN_HEADER (I think that's the name) at the top and to use bindgen. If you try to directly introduce a pointer, you'll likely crash the interpreter. There currently isn't any mechanism for passing in a pointer that the interpreter doesn't own. So the interpreter would think it had a refcount and damage the pointer. The interpreter could be extended to say "push this pointer, it's not refcounted", but then the caller would be responsible for handling the pointer, and there wouldn't be a destroy hook for it.

> Can the interpreter stopped by the host program? Without loss of data?

No and no. If the interpreter spins into an infinite loop, there's not a lot you can do. At best you could spray check opcodes/write in an opcode check counter that would throw an error if the controller doesn't want to resume the interpreter after N number of opcodes. The former approach is what browsers do so they can deliver that "this script seems to be slow, wanna stop it?", I think. It's not an area I'm too interested in exploring though.

> (Theoretically speaking of course, given there was some kind of audit) how feasible do you think is it to point untrusted code sources like the internet towards a running interpreter? Easy? Hard? Architecturally impossible?

It's possible. Today's MUD derivatives like MUCK and MUX already do that. They provide interpreters that are pretty basic (their focuses are more on adding functionality by functions versus exceptions/pattern matching/typing/etc.). But basic is good enough for a lot of people. They way they make it work is by heavily jailing what people can do. It's largely putting quotas on people for memory usage (no super big objects), time constraints, and permissions (I shouldn't be able to modify certain attributes of others, and wizards to ban people who misbehave). Rate limiting output is important too (no spamming of others or of commands.

Lily requires tables of class information and literals are permanently interned in the language (lambdas too). Same for types (someone could create a script that builds a series of different types to exhaust internal memory). It's possible, but Lily's a lot more complex than a lot of those kinds of languages, especially because of typing. It'd require a lot of modification that I don't think I'd want to do because it could end up compromising typical performance.

**Comment by sauer2** [comment]
Thanks!

I came up with those questions mostly because I found [this](https://www.reddit.com/r/ProgrammingLanguages/comments/7poi8q/should_an_embeddable_scripting_language_support/?st=jcayrbvw&sh=1d0d9e3d) discussion. 
Judging from the answers Lily is mostly on the "no" side.

> It's possible. Today's MUD derivatives like MUCK and MUX already do that. They provide interpreters that are pretty basic (their focuses are more on adding functionality by functions versus exceptions/pattern matching/typing/etc.). But basic is good enough for a lot of people. They way they make it work is by heavily jailing what people can do. It's largely putting quotas on people for memory usage (no super big objects), time constraints, and permissions (I shouldn't be able to modify certain attributes of others, and wizards to ban people who misbehave). Rate limiting output is important too (no spamming of others or of commands.

Ah, cool, I always wondered how they sandboxed Pike.

**Comment by FascinatedBox** [comment]
Closing this as part of the gitlab migration: https://gitlab.com/FascinatedBox/lily/issues/363
